// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCytZZEvBpfLrRkK-9aHhYwEbCi9T_FRQc',
    appId: '1:325359334304:web:0dfb080ef8c8bbb61beac5',
    messagingSenderId: '325359334304',
    projectId: 'fitness-workout-72800',
    authDomain: 'fitness-workout-72800.firebaseapp.com',
    storageBucket: 'fitness-workout-72800.firebasestorage.app',
    measurementId: 'G-0H19LMVGC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBocmi6Tb_RIqKUntk8R1-i2ABdZpHRQag',
    appId: '1:325359334304:android:70b4bba41ae6cd131beac5',
    messagingSenderId: '325359334304',
    projectId: 'fitness-workout-72800',
    storageBucket: 'fitness-workout-72800.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3FmPI84A1md3NkTJmYgtZqP5EroYeuGk',
    appId: '1:325359334304:ios:c6075240fa7869a41beac5',
    messagingSenderId: '325359334304',
    projectId: 'fitness-workout-72800',
    storageBucket: 'fitness-workout-72800.firebasestorage.app',
    iosBundleId: 'com.codeforany.fitness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCytZZEvBpfLrRkK-9aHhYwEbCi9T_FRQc',
    appId: '1:325359334304:web:d6326f3d30040c0a1beac5',
    messagingSenderId: '325359334304',
    projectId: 'fitness-workout-72800',
    authDomain: 'fitness-workout-72800.firebaseapp.com',
    storageBucket: 'fitness-workout-72800.firebasestorage.app',
    measurementId: 'G-PC8ZV99X4J',
  );
}
